Check for xz

diff --git a/build b/build
--- a/build
+++ b/build
@@ -14,6 +14,13 @@ CWD="$(pwd)"
 # only root can continue, because only root can read all files from your system
 allow_only_root
 
+# check for xz
+if [ "$(xz --help 2>&1 | grep -i "Compress")" = "" ]; then
+   echo "xz not found or cannot compress"
+   echo "you may consider installing xz-tools package"
+   exit 1
+fi
+
 # check for mksquashfs with xz compression
 if [ "$(mksquashfs 2>&1 | grep "Xdict-size")" = "" ]; then
    echo "mksquashfs not found or doesn't support -comp xz, aborting, no changes made"
